name: CI pipeline

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        strategy:
            matrix:
                # node-version: [12.x, 14.x, 15.x]
                node-version: [15.x]

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm ci
            - name: Build Library
              run: npm run build
            - name: Build Demo
              run: npm run build:demo
            # - run: npm run lint
            # - run: npm test -- --coverage
            - name: Deploy Demo to GitPages
              if: startsWith(matrix.node-version, '15')
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
              run: |
                  npm run deploy
