name: Node.js Package

on:
  release:
    branches: [master]
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}